"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-v+xyp-zo_c=(0_7k*y6f)f$p)^zu4+ievhkj@q5h*5frt&)rqq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'drf_spectacular',

    # Local apps
    'scanner.apps.ScannerConfig',
    'api.apps.ApiConfig',
    'reports.apps.ReportsConfig',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 정적 파일 서빙
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - SessionMiddleware 다음에 위치
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 보안 미들웨어 (해킹 방어)
    'core.middleware.SecurityMiddleware',
    'core.middleware.IPBlockingMiddleware',
    'core.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 전역 templates 디렉토리
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL 환경 변수가 있으면 사용, 없으면 SQLite 사용 (개발용)
DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'  # 한국어

TIME_ZONE = 'UTC'  # 서버는 UTC 사용, 프론트엔드에서 한국 시간으로 변환

USE_I18N = True

USE_TZ = True  # Timezone-aware datetimes 사용


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise 설정 - Django가 직접 정적 파일 서빙
WHITENOISE_AUTOREFRESH = DEBUG  # 개발 모드에서는 자동 새로고침
WHITENOISE_COMPRESS_OFFLINE = not DEBUG  # 프로덕션에서만 압축
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files (사용자 업로드 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CORS 설정
# ==============================================================================

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',  # 프론트엔드 개발 서버 (필요시)
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# ==============================================================================
# REST Framework 설정
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',  # 익명 사용자: 시간당 1000회 (개발용)
        'user': '10000/hour',  # 인증된 사용자: 시간당 10000회 (개발용)
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# API 문서화 (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Weak - Web Vulnerability Scanner API',
    'DESCRIPTION': '웹 취약점 스캔 API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ==============================================================================
# Celery 설정
# ==============================================================================

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'  # Celery도 UTC 사용
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30분
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25분
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50


# ==============================================================================
# 캐싱 설정 (Redis)
# ==============================================================================

CACHES = {
    'default': {
        # 개발 환경: 로컬 메모리 캐시 (Redis 없이도 작동)
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'weak-cache',
        'TIMEOUT': 300,  # 5분
    }
}

# 프로덕션에서는 Redis 사용 권장:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
#         'KEY_PREFIX': 'weak',
#         'TIMEOUT': 300,
#     }
# }


# ==============================================================================
# 로깅 설정
# ==============================================================================

# logs 디렉토리 생성
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'suppress_https_errors': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: 'HTTPS' not in record.getMessage() if hasattr(record, 'getMessage') else True
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['suppress_https_errors'],
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'scanner.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'error.log',
            'level': 'ERROR',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file'],  # 콘솔에 출력하지 않음 (인코딩 에러 방지)
            'level': 'INFO',
            'propagate': False,
        },
        'scanner': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ==============================================================================
# 스캔 설정 (커스텀)
# ==============================================================================

# 스캔 타임아웃 (초)
SCAN_TIMEOUT = config('SCAN_TIMEOUT', default=300, cast=int)

# 최대 크롤링 깊이
MAX_CRAWL_DEPTH = config('MAX_CRAWL_DEPTH', default=3, cast=int)

# 스캔할 최대 페이지 수
MAX_PAGES_TO_SCAN = config('MAX_PAGES_TO_SCAN', default=50, cast=int)

# User-Agent
USER_AGENT = config('USER_AGENT', default='Weak-Scanner/1.0 (Educational Purpose)')

# 동시 스캔 제한 (0 = 무제한, 1+ = 최대 동시 스캔 개수)
MAX_CONCURRENT_SCANS = config('MAX_CONCURRENT_SCANS', default=0, cast=int)

# 차단할 IP 대역 (SSRF 방지)
BLOCKED_IP_RANGES = [
    '127.0.0.0/8',     # Loopback
    '10.0.0.0/8',      # Private
    '172.16.0.0/12',   # Private
    '192.168.0.0/16',  # Private
    '169.254.0.0/16',  # Link-local
    '::1/128',         # IPv6 loopback
    'fc00::/7',        # IPv6 private
]

# 스캔 결과 보관 기간 (일)
SCAN_RESULTS_RETENTION_DAYS = 7

# 외부 API 설정 (선택사항)
W3C_VALIDATOR_API = 'https://validator.w3.org/nu/'
W3C_CSS_VALIDATOR_API = 'https://jigsaw.w3.org/css-validator/validator'


# ==============================================================================
# 세션 설정
# ==============================================================================

# 세션 백엔드 설정 (개발 환경용)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 1일
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True

# ==============================================================================
# 보안 설정
# ==============================================================================

# 프로덕션 환경에서는 다음 설정들을 활성화하세요
if not DEBUG:
    # Cloudflare나 리버스 프록시가 HTTPS를 처리하는 경우 False로 설정
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Cloudflare/리버스 프록시 사용 시 설정
if config('USE_X_FORWARDED_HOST', default=False, cast=bool):
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
