# Generated by Django 5.2.8 on 2025-11-26 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048, verbose_name='스캔 URL')),
                ('target_domain', models.CharField(max_length=255, verbose_name='대상 도메인')),
                ('scan_types', models.JSONField(default=list, help_text='["security", "standards", "accessibility"]', verbose_name='스캔 유형')),
                ('deep_scan', models.BooleanField(default=False, verbose_name='심층 스캔')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.CharField(max_length=500, verbose_name='User Agent')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='작업 ID')),
            ],
            options={
                'verbose_name': '스캔 요청',
                'verbose_name_plural': '스캔 요청 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scanner_sca_created_0d76e0_idx'), models.Index(fields=['status'], name='scanner_sca_status_c2ed31_idx'), models.Index(fields=['target_domain'], name='scanner_sca_target__675403_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, verbose_name='전체 점수 (0-100)')),
                ('wcag_level', models.CharField(choices=[('AAA', 'WCAG AAA'), ('AA', 'WCAG AA'), ('A', 'WCAG A'), ('None', '미달')], default='None', max_length=10, verbose_name='WCAG 등급')),
                ('perceivable_issues', models.JSONField(default=list, verbose_name='인식 가능성 이슈')),
                ('operable_issues', models.JSONField(default=list, verbose_name='운용 가능성 이슈')),
                ('understandable_issues', models.JSONField(default=list, verbose_name='이해 가능성 이슈')),
                ('robust_issues', models.JSONField(default=list, verbose_name='견고성 이슈')),
                ('aria_errors', models.JSONField(default=list, verbose_name='ARIA 에러')),
                ('aria_warnings', models.JSONField(default=list, verbose_name='ARIA 경고')),
                ('keyboard_navigation', models.JSONField(default=dict, verbose_name='키보드 네비게이션')),
                ('color_contrast', models.JSONField(default=list, verbose_name='색상 대비')),
                ('screen_reader_issues', models.JSONField(default=list, verbose_name='스크린 리더 이슈')),
                ('alt_text_missing', models.JSONField(default=list, verbose_name='대체 텍스트 누락')),
                ('heading_structure', models.JSONField(default=dict, verbose_name='제목 구조')),
                ('form_labels', models.JSONField(default=list, verbose_name='폼 레이블')),
                ('total_issues', models.IntegerField(default=0, verbose_name='전체 이슈 수')),
                ('critical_issues', models.IntegerField(default=0, verbose_name='치명적 이슈 수')),
                ('serious_issues', models.IntegerField(default=0, verbose_name='심각한 이슈 수')),
                ('moderate_issues', models.IntegerField(default=0, verbose_name='보통 이슈 수')),
                ('minor_issues', models.IntegerField(default=0, verbose_name='경미한 이슈 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('scan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_result', to='scanner.scanrequest', verbose_name='스캔 요청')),
            ],
            options={
                'verbose_name': '접근성 결과',
                'verbose_name_plural': '접근성 결과 목록',
            },
        ),
        migrations.CreateModel(
            name='SecurityScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, verbose_name='전체 점수 (0-100)')),
                ('risk_level', models.CharField(choices=[('critical', '치명적'), ('high', '높음'), ('medium', '중간'), ('low', '낮음'), ('info', '정보')], default='info', max_length=20, verbose_name='위험 수준')),
                ('sql_injection', models.JSONField(default=dict, verbose_name='SQL Injection')),
                ('xss_vulnerabilities', models.JSONField(default=dict, verbose_name='XSS 취약점')),
                ('csrf_protection', models.JSONField(default=dict, verbose_name='CSRF 보호')),
                ('insecure_deserialization', models.JSONField(default=dict, verbose_name='안전하지 않은 역직렬화')),
                ('xml_external_entities', models.JSONField(default=dict, verbose_name='XXE')),
                ('broken_access_control', models.JSONField(default=dict, verbose_name='접근 제어 오류')),
                ('security_misconfiguration', models.JSONField(default=dict, verbose_name='보안 설정 오류')),
                ('sensitive_data_exposure', models.JSONField(default=dict, verbose_name='민감 데이터 노출')),
                ('insufficient_logging', models.JSONField(default=dict, verbose_name='불충분한 로깅')),
                ('vulnerable_components', models.JSONField(default=dict, verbose_name='취약한 컴포넌트')),
                ('security_headers', models.JSONField(default=dict, verbose_name='보안 헤더')),
                ('ssl_tls_result', models.JSONField(default=dict, verbose_name='SSL/TLS 결과')),
                ('clickjacking', models.JSONField(default=dict, verbose_name='클릭재킹')),
                ('cors_misconfiguration', models.JSONField(default=dict, verbose_name='CORS 설정 오류')),
                ('open_redirects', models.JSONField(default=dict, verbose_name='오픈 리다이렉트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('scan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_result', to='scanner.scanrequest', verbose_name='스캔 요청')),
            ],
            options={
                'verbose_name': '보안 스캔 결과',
                'verbose_name_plural': '보안 스캔 결과 목록',
            },
        ),
        migrations.CreateModel(
            name='WebStandardsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, verbose_name='전체 점수 (0-100)')),
                ('html_valid', models.BooleanField(default=False, verbose_name='HTML 유효성')),
                ('html_errors', models.JSONField(default=list, verbose_name='HTML 에러')),
                ('html_warnings', models.JSONField(default=list, verbose_name='HTML 경고')),
                ('html_error_count', models.IntegerField(default=0, verbose_name='HTML 에러 수')),
                ('css_valid', models.BooleanField(default=False, verbose_name='CSS 유효성')),
                ('css_errors', models.JSONField(default=list, verbose_name='CSS 에러')),
                ('css_warnings', models.JSONField(default=list, verbose_name='CSS 경고')),
                ('css_error_count', models.IntegerField(default=0, verbose_name='CSS 에러 수')),
                ('js_errors', models.JSONField(default=list, verbose_name='JavaScript 에러')),
                ('js_console_logs', models.JSONField(default=list, verbose_name='콘솔 로그')),
                ('js_error_count', models.IntegerField(default=0, verbose_name='JS 에러 수')),
                ('seo_score', models.IntegerField(default=0, verbose_name='SEO 점수')),
                ('seo_issues', models.JSONField(default=list, verbose_name='SEO 이슈')),
                ('meta_tags', models.JSONField(default=dict, verbose_name='메타 태그')),
                ('page_load_time', models.FloatField(blank=True, null=True, verbose_name='페이지 로드 시간 (초)')),
                ('page_size', models.IntegerField(blank=True, null=True, verbose_name='페이지 크기 (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('scan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standards_result', to='scanner.scanrequest', verbose_name='스캔 요청')),
            ],
            options={
                'verbose_name': '웹 표준 결과',
                'verbose_name_plural': '웹 표준 결과 목록',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('security', '보안'), ('standards', '웹 표준'), ('accessibility', '접근성')], max_length=100, verbose_name='카테고리')),
                ('vulnerability_type', models.CharField(max_length=100, verbose_name='취약점 유형')),
                ('severity', models.CharField(choices=[('critical', '치명적'), ('high', '높음'), ('medium', '중간'), ('low', '낮음'), ('info', '정보')], max_length=20, verbose_name='심각도')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('affected_url', models.URLField(max_length=2048, verbose_name='영향받는 URL')),
                ('affected_element', models.CharField(blank=True, max_length=500, verbose_name='영향받는 요소')),
                ('evidence', models.TextField(blank=True, verbose_name='증거')),
                ('recommendation', models.TextField(verbose_name='권장 사항')),
                ('cve_id', models.CharField(blank=True, max_length=50, verbose_name='CVE ID')),
                ('cwe_id', models.CharField(blank=True, max_length=50, verbose_name='CWE ID')),
                ('owasp_category', models.CharField(blank=True, max_length=100, verbose_name='OWASP 카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('scan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scanrequest', verbose_name='스캔 요청')),
            ],
            options={
                'verbose_name': '취약점',
                'verbose_name_plural': '취약점 목록',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['scan_request', 'severity'], name='scanner_vul_scan_re_0004a9_idx'), models.Index(fields=['category'], name='scanner_vul_categor_0f93a2_idx')],
            },
        ),
    ]
