# Generated by Django 5.2.8 on 2025-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityresult',
            name='scanner_metadata',
            field=models.JSONField(default=list, verbose_name='스캐너 메타데이터'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='scanner_metadata',
            field=models.JSONField(default=list, verbose_name='스캐너 메타데이터'),
        ),
        migrations.AddField(
            model_name='webstandardsresult',
            name='scanner_metadata',
            field=models.JSONField(default=list, verbose_name='스캐너 메타데이터'),
        ),
    ]
