# Generated by Django 5.2.8 on 2025-11-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_accessibilityresult_scanner_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='command_injection',
            field=models.JSONField(default=dict, verbose_name='Command Injection'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='deserialization',
            field=models.JSONField(default=dict, verbose_name='Deserialization 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='file_upload',
            field=models.JSONField(default=dict, verbose_name='파일 업로드 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='jwt_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='JWT 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='nosql_injection',
            field=models.JSONField(default=dict, verbose_name='NoSQL Injection'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='path_traversal',
            field=models.JSONField(default=dict, verbose_name='경로 순회 공격'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='ssl_tls_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='SSL/TLS 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='ssrf_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='SSRF 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='template_injection',
            field=models.JSONField(default=dict, verbose_name='템플릿 주입'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='xxe_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='XXE 취약점'),
        ),
    ]
