# Generated by Django 5.2.8 on 2025-11-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_securityscanresult_command_injection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='authorization_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='Authorization 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='graphql_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='GraphQL 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='ldap_injection',
            field=models.JSONField(default=dict, verbose_name='LDAP Injection'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='oauth_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='OAuth 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='password_policy',
            field=models.JSONField(default=dict, verbose_name='비밀번호 정책'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='rate_limiting',
            field=models.JSONField(default=dict, verbose_name='Rate Limiting'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='rest_api_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='REST API 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='session_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='Session 취약점'),
        ),
    ]
