# Generated by Django 5.2.8 on 2025-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_securityscanresult_authorization_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='exception_handling_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='Exception Handling 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='supply_chain_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='Supply Chain 취약점'),
        ),
    ]
