# Generated by Django 5.2.8 on 2025-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_securityscanresult_exception_handling_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='account_enumeration_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='계정 열거 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='business_logic_anomaly_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='비즈니스 로직 이상'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='logging_monitoring_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='로깅/모니터링 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='price_manipulation_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='가격 조작 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='race_condition_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='레이스 컨디션 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='resource_exhaustion_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='리소스 소진 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='workflow_bypass_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='워크플로우 우회 취약점'),
        ),
    ]
