# Generated by Django 5.2.8 on 2025-11-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_securityscanresult_account_enumeration_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='api_integrity_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='API 무결성 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='checksum_validation_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='체크섬 검증 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='jwt_advanced_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='JWT 고급 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='license_compliance_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='라이선스 준수 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='outdated_dependency_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='오래된 종속성 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='package_integrity_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='패키지 무결성 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='serialization_integrity_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='직렬화 무결성 취약점'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='typosquatting_vulnerabilities',
            field=models.JSONField(default=dict, verbose_name='타이포스쿼팅 취약점'),
        ),
    ]
