# Generated by Django 5.2.8 on 2025-12-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_securityscanresult_api_integrity_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='프리셋 이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('configurations', models.JSONField(default=dict, help_text='scanner_id별 설정 (enabled, show_in_results 등)', verbose_name='설정')),
                ('is_active', models.BooleanField(default=False, verbose_name='현재 활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '스캐너 프리셋',
                'verbose_name_plural': '스캐너 프리셋',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScannerConfiguration',
            fields=[
                ('scanner_id', models.CharField(help_text='스캐너 클래스의 metadata["id"] 값', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='스캐너 ID')),
                ('name', models.CharField(max_length=200, verbose_name='스캐너 이름')),
                ('category', models.CharField(choices=[('security', '보안'), ('standards', '웹 표준'), ('accessibility', '접근성')], max_length=50, verbose_name='카테고리')),
                ('icon', models.CharField(default='🔍', max_length=10, verbose_name='아이콘')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('enabled', models.BooleanField(default=True, help_text='스캔 시 이 스캐너를 실행할지 여부', verbose_name='활성화')),
                ('timeout', models.IntegerField(default=30, help_text='스캐너 실행 시간 제한', verbose_name='타임아웃(초)')),
                ('weight', models.FloatField(default=1.0, help_text='진행률 계산 시 가중치', verbose_name='가중치')),
                ('show_in_results', models.BooleanField(default=True, help_text='스캔 결과 페이지에 이 스캐너 결과를 표시할지 여부', verbose_name='결과 표시')),
                ('show_details', models.BooleanField(default=True, help_text='결과의 상세 정보를 표시할지 여부', verbose_name='상세 정보 표시')),
                ('show_if_passed', models.BooleanField(default=True, help_text='테스트를 통과했을 때도 표시할지 여부', verbose_name='통과 시 표시')),
                ('show_if_failed', models.BooleanField(default=True, help_text='테스트를 실패했을 때 표시할지 여부', verbose_name='실패 시 표시')),
                ('display_order', models.IntegerField(default=0, help_text='결과 페이지에서의 표시 순서 (낮을수록 먼저 표시)', verbose_name='표시 순서')),
                ('custom_pass_message', models.TextField(blank=True, help_text='테스트 통과 시 표시할 커스텀 메시지 (선택사항)', verbose_name='통과 커스텀 메시지')),
                ('custom_fail_message', models.TextField(blank=True, help_text='테스트 실패 시 표시할 커스텀 메시지 (선택사항)', verbose_name='실패 커스텀 메시지')),
                ('total_runs', models.IntegerField(default=0, verbose_name='총 실행 횟수')),
                ('total_failures', models.IntegerField(default=0, verbose_name='실패 횟수')),
                ('avg_duration', models.FloatField(default=0.0, verbose_name='평균 실행 시간(초)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 실행 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '스캐너 설정',
                'verbose_name_plural': '스캐너 설정',
                'ordering': ['category', 'display_order', 'scanner_id'],
                'indexes': [models.Index(fields=['category', 'enabled'], name='scanner_sca_categor_75a3c3_idx'), models.Index(fields=['enabled'], name='scanner_sca_enabled_56b3f1_idx')],
            },
        ),
    ]
