# Generated by Django 5.2.8 on 2025-12-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scannerpreset_scannerconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscanresult',
            name='directory_listing',
            field=models.JSONField(default=dict, verbose_name='디렉토리 리스팅'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='http_method',
            field=models.JSONField(default=dict, verbose_name='HTTP 메서드'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='mixed_content',
            field=models.JSONField(default=dict, verbose_name='Mixed Content'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='sensitive_file',
            field=models.JSONField(default=dict, verbose_name='민감한 파일 노출'),
        ),
        migrations.AddField(
            model_name='securityscanresult',
            name='subresource_integrity',
            field=models.JSONField(default=dict, verbose_name='SRI'),
        ),
    ]
